### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by mozzee** [pingw33n/munin-kannel-plugins#2]
[root@sms plugins]# munin-run kannel_single
Traceback (most recent call last):
  File "/etc/munin/plugins/kannel_single", line 70, in <module>
    print_data()
  File "/etc/munin/plugins/kannel_single", line 53, in print_data
    status = kannel_util.get_status()
  File "/usr/share/munin/plugins/kannel_util.py", line 35, in get_status
    'sms': int(el.findtext('received/sms')),
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by pingw33n** [comment]
Thanks for reporting, should be fixed now :)

**Comment by mozzee** [comment]
Perfect, Thank you very much. working like a charm :)
